### ISSUE TITLE
Could not find template js_init_inheritance

### ISSUE THREAD

**Issue by Andy-zhujunwen** [mmomtchev/swig-napi-example-project#139]
my swig version is 4.2.0. it can not support the shared_ptr, so i find this repo, and copy the Lib/javascript to my project, but when i generate my code, there is a error : Could not find template js_init_inheritance

so i want to kwon why it happened? and how to fix it.

**Comment by mmomtchev** [comment]
How did you know that you had to tell me that it was version 4.2.0 when SWIG JSE starts at 5.0?

I will tell you how, it is because the Sun King, after 20 years as the "head" of an "IT" company, who still believes that engineers grow on trees and you buy them by the kilo, is not able to find anyone who is able to go deeper than reading the commit messages and the comments: https://github.com/mmomtchev/magickwand.js/pull/219/commits/c78a17b87cdb073c393a396887116ac2f06ff582
